import re
# Outers
from .....exceptions import ParamError


def raise_regex_param_invalid_pattern_error(
    pattern: str,
    err: re.error,
) -> None:
    """Raise a ParamError (ValueError) tailored to an invalid regex pattern in the Regex rule."""

    # 1. Build and raise the exception
    raise ParamError(
        error_name="INVALID_REGEX_PATTERN_ERROR",
        label="Regex.pattern",
        expected="valid regular expression syntax",
        value=pattern,
        problem=f"Invalid regex pattern /{pattern}/: {err}.",
        how_to_fix=(
            "Provide a syntactically correct regular expression pattern.",
            "Example: Regex(r'^[a-z]+$')",
        ),
        exception=ValueError,
    )


_DESIGN_NOTES = """
# raise_regex_param_invalid_pattern_error — Regex Pattern Syntax Guard

## Purpose
Raises a tailored `ParamError` wrapping Python's internal `re.error` when an
invalid regex string is passed during `Regex` instantiation.

---

## 1. Execution Rationale

* **Early Compilation Diagnostics:**
  Catches invalid regular expressions at rule initialization time rather
  than during runtime evaluation, avoiding repeated compilation failures.
* **Underlying Engine Error Passthrough:**
  Embeds the exact error message generated by Python's `re` module (`err`)
  directly into the `problem` field for clear syntax debugging.
"""
