"""Tests for the AnyOf container rule."""

from typing import Any
import pytest

# Testing tools and Kwargs wrapper
from simplibs.exception.testing import assert_exception_function, Kwargs
from simplibs.validate.testing import assert_rule_contract

# Exceptions
from simplibs.validate.exceptions import ValidateError

# Rules
from simplibs.validate.rules.containers import AnyOf
from simplibs.validate.rules.predicates.numeric import IsInteger, IsFloat
from simplibs.validate.rules.predicates.strings import IsString


# ==============================================================================
# 1. MASTER CONTRACT TEST
# ==============================================================================

def test_any_of_contract(subtests):
    """Verify the complete contract of AnyOf using the master orchestrator."""
    # Accepts int OR float
    rule = AnyOf(IsInteger(), IsFloat())

    assert_rule_contract(
        subtests,
        rule=rule,
        valid_values=[10, 10.5, -5, 0.0],         # Satisfies at least one rule
        invalid_values=["string", [1, 2], None],  # Neither integer nor float
        rule_factory=AnyOf,
        invalid_init_params=[
            ((), {}),  # AnyOf() with no arguments raises ParamError
        ],
        check_raise_invalid=True,
        deep_check=True,
        verbose=False,
    )


# ==============================================================================
# 2. DIAGNOSTIC CARD TEST (Generated by AnyOf itself)
# ==============================================================================

def test_any_of_exception_details(subtests):
    """Verify exact diagnostic card details when a value fails to satisfy any rule."""
    rule = AnyOf(IsInteger(), IsFloat())

    assert_exception_function(
        subtests,
        func=rule.validate,
        invalid_params=("abc", Kwargs(value_name="payload")),
        exception_type=ValidateError,
        error_name="ANY_OF_ERROR",
        label="payload",
        expected="value satisfying at least one of:",
        problem="Value did not satisfy any of:",
        how_to_fix="Provide a value that satisfies at least one of:",
        exception=ValueError,
        verbose=False,
    )


# ==============================================================================
# 3. SELF-FLATTENING CONSTRUCTOR & OPERATOR CHAINING
# ==============================================================================

def test_any_of_self_flattening(subtests):
    """Verify that AnyOf automatically flattens nested AnyOf instances into a single flat structure."""
    r1, r2, r3 = IsInteger(), IsFloat(), IsString()

    with subtests.test("manual_nested_instantiation"):
        # AnyOf(AnyOf(r1, r2), r3) -> should create flat AnyOf(r1, r2, r3)
        rule = AnyOf(AnyOf(r1, r2), r3)
        assert len(rule.rules) == 3
        assert rule.rules == (r1, r2, r3)

    with subtests.test("operator_or_chaining"):
        # r1 | r2 | r3 -> evaluates as (r1 | r2) | r3
        rule = r1 | r2 | r3
        assert isinstance(rule, AnyOf)
        assert len(rule.rules) == 3
        assert rule.rules == (r1, r2, r3)


# ==============================================================================
# 4. EDGE CASES & SHORT-CIRCUIT EVALUATION
# ==============================================================================

def test_any_of_short_circuit_eval():
    """Verify that AnyOf evaluates rules left-to-right and stops on the first success."""
    call_log = []

    def rule_1(val):
        call_log.append("rule_1")
        return True  # First rule passes immediately

    def rule_2(val):
        call_log.append("rule_2")
        return False

    rule = AnyOf(rule_1, rule_2)

    assert rule.is_valid(10) is True
    assert call_log == ["rule_1"]