from typing import Any, Callable
# Outers
from ...exceptions import ValidationError
from ..base_class import Rule
from ..predicates.introspection import IsIterable
# Inners
from ._helpers import as_predicate, build_child_exception
from ._init_validators import raise_rule_param_not_callable


class ForEach(Rule):
    """Every item in an iterable value must satisfy the given rule.

    Rule:
        all(rule(item) for item in value)

    Example:
        validate(values, ForEach(IsInteger()))
    """

    __slots__ = ("rule",)

    # ----------------------------------------------------------------------
    # Constructor initialization
    # ----------------------------------------------------------------------
    def __init__(self, rule: Rule | Callable[[Any], bool]) -> None:

        # 1. Parameter validation
        if not callable(rule):
            raise_rule_param_not_callable("ForEach", rule)

        # 2. Parameter assignment
        self.rule = rule

    # ----------------------------------------------------------------------
    # Rule definition
    # ----------------------------------------------------------------------
    def is_valid(self, value: Any) -> bool:

        # 1. Obtain an iterator from the value
        try:
            items = iter(value)
        except TypeError:
            return False

        # 2. Evaluate the rule for every item
        predicate = as_predicate(self.rule)
        return all(predicate(item) for item in items)

    # ----------------------------------------------------------------------
    # Exception definition
    # ----------------------------------------------------------------------
    def build_exception(
        self,
        value: Any,
        value_name: str | None = None,
        context: str | None = None,
    ) -> Exception:

        # 1. Check whether the value is iterable
        try:
            items = list(value)
        except TypeError:
            return IsIterable().build_exception(value, value_name, context)

        # 2. Find the first item that fails the rule and build a child exception
        predicate = as_predicate(self.rule)
        for index, item in enumerate(items):
            if not predicate(item):
                item_name = (
                    f"{value_name}[{index}]" if value_name else f"[{index}]"
                )
                return build_child_exception(self.rule, item, item_name, context)

        # 3. Fallback (build exception if all items unexpectedly passed)
        return ValidationError(
            error_name="FOR_EACH_UNREACHABLE_ERROR",
            label=value_name,
            expected="iterable with all items passing the rule",
            value=value,
            problem="All items unexpectedly passed during error construction.",
            context=context,
            how_to_fix=("Check collection items state.",),
            exception=RuntimeError,
        )


_DESIGN_NOTES = """
# ForEach — Collection Element Validation Container Rule

## Purpose
The `ForEach` rule applies a target validation rule or callable predicate to
every individual element within an input iterable container.

---

## 1. Execution Rationale & Delegated Non-Iterable Handling

* **Constructor Safety Guard:**
  Ensures the inner `rule` is either an instance of `Rule` or a callable
  object.
* **Iterator Inspection:**
  Attempts `iter(value)` during `is_valid`. Safely catches `TypeError` for
  non-iterable inputs and returns `False`.
* **Non-iterable Exception Delegation:**
  If `value` is non-iterable when `build_exception` is called, delegates
  exception creation to `IsIterable().build_exception(value, value_name,
  context)` (`TypeError`).
* **Index Path Propagation:**
  Constructs child item labels using indexed syntax (e.g., `user_ids[3]`),
  passing precise item location down to the child exception builder.

---

## 2. Exception Card Design

* **Transparent Sub-rule Delegation:**
  Directly vends the exact exception card generated by the failing sub-rule
  for the failing element.
"""
